env: "LOCAL"
http_server:
  address: "0.0.0.0:8081"
  timeout: 5s
  idle_timeout: 60s
postgres:
  host: 'localhost:5435'
  user: 'admin'
  database: 'RapidURL'
memcached:
  hosts:
    - "localhost:11211"